---
- hosts: CSR1
  gather_facts: false
  connection: local
  tasks: 
    ios_command:
      commands:
      - hostname CSR1
      - int G2
      - ip addr 10.10.1.1 255.255.255.0
      - no shut
    
    
    
