---
- hosts: webservers
  gather_facts: no
  remote_user: justincase

  tasks: 
  - name: Copy website to webserver
    become: yes
    ansible.builtin.copy:
      src: /home/justincase/Downloads/duckfarmstatic/
      dest: /var/www/html/