---
# tasks file for roles/backup-conf

- name: print running conf
  ios_command:
    commands: show run | exclude !
  register: output_router

- name: save conf
  copy:
    content: "{{ output_router.stdout[0] }}"
    dest: "/home/justincase/Git/IT_385/iOS_backups/show_run_{{ inventory_hostname }}.txt"